// Generated by gencpp from file package/addint.msg
// DO NOT EDIT!


#ifndef PACKAGE_MESSAGE_ADDINT_H
#define PACKAGE_MESSAGE_ADDINT_H

#include <ros/service_traits.h>


#include <package/addintRequest.h>
#include <package/addintResponse.h>


namespace package
{

struct addint
{

typedef addintRequest Request;
typedef addintResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addint
} // namespace package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::package::addint > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::package::addint&) { return value(); }
};

template<>
struct DataType< ::package::addint > {
  static const char* value()
  {
    return "package/addint";
  }

  static const char* value(const ::package::addint&) { return value(); }
};


// service_traits::MD5Sum< ::package::addintRequest> should match
// service_traits::MD5Sum< ::package::addint >
template<>
struct MD5Sum< ::package::addintRequest>
{
  static const char* value()
  {
    return MD5Sum< ::package::addint >::value();
  }
  static const char* value(const ::package::addintRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::package::addintRequest> should match
// service_traits::DataType< ::package::addint >
template<>
struct DataType< ::package::addintRequest>
{
  static const char* value()
  {
    return DataType< ::package::addint >::value();
  }
  static const char* value(const ::package::addintRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::package::addintResponse> should match
// service_traits::MD5Sum< ::package::addint >
template<>
struct MD5Sum< ::package::addintResponse>
{
  static const char* value()
  {
    return MD5Sum< ::package::addint >::value();
  }
  static const char* value(const ::package::addintResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::package::addintResponse> should match
// service_traits::DataType< ::package::addint >
template<>
struct DataType< ::package::addintResponse>
{
  static const char* value()
  {
    return DataType< ::package::addint >::value();
  }
  static const char* value(const ::package::addintResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACKAGE_MESSAGE_ADDINT_H
