// Generated by gencpp from file package/integer.msg
// DO NOT EDIT!


#ifndef PACKAGE_MESSAGE_INTEGER_H
#define PACKAGE_MESSAGE_INTEGER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package
{
template <class ContainerAllocator>
struct integer_
{
  typedef integer_<ContainerAllocator> Type;

  integer_()
    : sum(0)  {
    }
  integer_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::package::integer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package::integer_<ContainerAllocator> const> ConstPtr;

}; // struct integer_

typedef ::package::integer_<std::allocator<void> > integer;

typedef boost::shared_ptr< ::package::integer > integerPtr;
typedef boost::shared_ptr< ::package::integer const> integerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package::integer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package::integer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package::integer_<ContainerAllocator1> & lhs, const ::package::integer_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package::integer_<ContainerAllocator1> & lhs, const ::package::integer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package::integer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package::integer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::integer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::integer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::integer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::integer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package::integer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::package::integer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::package::integer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package/integer";
  }

  static const char* value(const ::package::integer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package::integer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n"
;
  }

  static const char* value(const ::package::integer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package::integer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct integer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package::integer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package::integer_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_MESSAGE_INTEGER_H
